"""Initial migration - create tickets table

Revision ID: 15a4e68f7283
Revises: 
Create Date: 2025-12-21 17:07:45.399747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a4e68f7283'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ANALYZING', 'WAITING_CONFIRM', 'DONE', 'MANUAL_REQUIRED', 'REJECTED', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('raw_voc', sa.Text(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SLACK', name='channel'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('suspected_type_primary', sa.String(length=50), nullable=True),
    sa.Column('suspected_type_secondary', sa.String(length=50), nullable=True),
    sa.Column('affected_system', sa.String(length=100), nullable=True),
    sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='urgency'), nullable=True),
    sa.Column('agent_decision_primary', sa.String(length=50), nullable=True),
    sa.Column('agent_decision_secondary', sa.String(length=50), nullable=True),
    sa.Column('decision_confidence', sa.Float(), nullable=True),
    sa.Column('decision_reason', sa.JSON(), nullable=True),
    sa.Column('action_proposal', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('manual_resolution', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_id'), 'tickets', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_tickets_urgency'), 'tickets', ['urgency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_urgency'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ticket_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
